import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

describe('current product status report', () => {
  it('keeps the repo-facing status report aligned with the restaurant growth AI OS boundary', () => {
    const doc = readFileSync(join(process.cwd(), 'docs/CURRENT_PRODUCT_STATUS.md'), 'utf8');

    expect(doc).toContain('餐饮门店增长 AI OS');
    expect(doc).toContain('/factory?variant=friend_trial');
    expect(doc).toContain('今天该做哪件事');
    expect(doc).toContain('restaurant-growth-loop-v1');
    expect(doc).toContain('Intake');
    expect(doc).toContain('Diagnose');
    expect(doc).toContain('Create');
    expect(doc).toContain('Publish Proof');
    expect(doc).toContain('Recover');
    expect(doc).toContain('Review Loop');
    expect(doc).toContain('任务、负责人、凭证、状态和下一步');
    expect(doc).toContain('筷子科技 / Kuaizi');
    expect(doc).toContain('美团智能掌柜');
    expect(doc).toContain('Slang / ConverseNow / Square Voice AI');
    expect(doc).toContain('Owner.com');
    expect(doc).toContain('SevenRooms');
    expect(doc).toContain('MarketMan');
    expect(doc).toContain('Otter / Deliverect / Toast / Popmenu');
    expect(doc).toContain('docs/WENAI_RESTAURANT_AI_OS_LONG_TERM_PROMPT.md');
    expect(doc).toContain('长期接管 prompt 与竞品参考来源');
    expect(doc).toContain('docs/EXTERNAL_INTEGRATION_MATERIALS.md');
    expect(doc).toContain('Publish Proof Board');
    expect(doc).toContain('src/lib/restaurant-publish-proof-ledger.ts');
    expect(doc).toContain('渠道、负责人、发布时间、链接/截图、状态、阻塞原因和脱敏回流信号');
    expect(doc).toContain('src/lib/restaurant-recover-signal-import.ts');
    expect(doc).toContain('只接收预约、券领取、咨询、评价、社群反馈、到店意向和核销的聚合数量');
    expect(doc).toContain('src/lib/restaurant-review-loop-boss-recap.ts');
    expect(doc).toContain('推哪道菜、改哪个卖点、补什么素材、谁跟进、是否放大/继续验证/暂停');
    expect(doc).toContain('src/lib/restaurant-review-loop-share-summary.ts');
    expect(doc).toContain('可转发 Review Loop 摘要合同');
    expect(doc).toContain('src/lib/restaurant-video-production-passport.ts');
    expect(doc).toContain('Create / Cut 视频生产护照合同');
    expect(doc).toContain('src/lib/restaurant-voice-frontdesk-gate.ts');
    expect(doc).toContain('语音/电话接待门禁合同');
    expect(doc).toContain('src/lib/restaurant-dish-cost-inventory-sample.ts');
    expect(doc).toContain('菜品成本/库存样表合同');
    expect(doc).toContain('src/lib/restaurant-competitor-capability-matrix.ts');
    expect(doc).toContain('竞品能力矩阵客户化合同');
    expect(doc).toContain('六段闭环、发布凭证账本和老板版下一轮复盘展示到 customer-facing 页面');
    expect(doc).toContain('朋友试用管理页已经展示同一套老板复盘摘要');
    expect(doc).toContain('/factory/cast');
    expect(doc).toContain('friend trial 和 Cast 共用同一套发布凭证合同');
    expect(doc).toContain('Demo / POC 阶段能真实展示');
    expect(doc).toContain('No provider callback');
    expect(doc).toContain('No platform authorization');
    expect(doc).toContain('No merchant activity authorization');
    expect(doc).toContain('No POS/redemption/member data contract');
    expect(doc).toContain('No audited scale ledger');
    expect(doc).toContain('91M+ creative output');
    expect(doc).toContain('42M+ video distribution');
    expect(doc).toContain('不保存手机号、微信号、私信原文、优惠码、订单明细、原始 POS 行、cookie、token、API key');
    expect(doc).toContain('粘贴导入模板');
    expect(doc).toContain('成本/库存粘贴模板入口');
    expect(doc).toContain('成本/库存安全导入演练');
    expect(doc).toContain('检查有效行/问题行/待补货');
    expect(doc).toContain('可转发前厅 SOP 摘要');
    expect(doc).toContain('docs/RESTAURANT_MIGRATION_AUDIT.md');
    expect(doc).toContain('docs/EXTERNAL_INTEGRATION_MATERIALS.md');
    expect(doc).toContain('外部材料按餐厅、渠道、发布凭证、脱敏回收、电话接待、成本库存和视频 provider 门禁组织');
    expect(doc).toContain('review token、RBAC、DLP、grant、fail-closed');
    expect(doc).toContain('完整 `scripts\\verify.ps1` 并通过');
    expect(doc).toContain('docs/RESTAURANT_DELIVERABLE_GROUPS.md');
    expect(doc).toContain('8 个可审、可测、可拆提交的交付组');
    expect(doc).toContain('README.md');
    expect(doc).toContain('docs/AI_CONTEXT.md');
    expect(doc).toContain('P0 | 分组复核 / 提交准备');
    expect(doc).toContain('P1 | 前厅接待摘要导出动作');
    expect(doc).toContain('P1 | 成本/库存导入交接记录');

    expect(doc).toContain('Phase 8 commit-prep snapshot');
    expect(doc).toContain('Review slices ready: 8/8');
    expect(doc).toContain('Suggested commit labels ready: 8/8');
    expect(doc).toContain('Verification result: passed');
    expect(doc).toContain('Focused suite result inside verify: 116 test files / 692 tests passed');
    expect(doc).toContain('Browser smoke verification');
    expect(doc).toContain('restaurant-friend-trial.spec.ts --project=chromium');
    expect(doc).toContain('feat(restaurant): gate advanced runtime provider work');
    expect(doc).toContain('no broad add; preserve unrelated edits; split review by the 8 delivery groups');

    expect(doc).not.toContain('SKU');
    expect(doc).not.toContain('定位为通用 AI 工具目录');
    expect(doc).not.toContain('已能一键成片完成');
    expect(doc).not.toContain('已能自动发布到大众点评/美团/小红书/抖音/微信社群');
    expect(doc).not.toContain('璇曡窇');
    expect(doc).not.toContain('绛峰瓙');
  });
});
